services:
  converter:
    build: ./converter
    container_name: converter
    ports:
      - "8081:8081"
    networks:
      - bridge-network

  generate-json:
    build: ./generateJson
    container_name: generateJson
    depends_on:
      - converter
    ports:
      - "8080:8080"
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge
